### ISSUE TITLE
Create User doesn't return anything

### ISSUE THREAD

**Issue by felixa1996** [0xb4lamx/nestjs-boilerplate-microservice#36]
![Screen Shot 2021-02-14 at 23 29 23](https://user-images.githubusercontent.com/75177762/107882538-7d7c5600-6f1c-11eb-8556-c7f555f98913.png)

**Comment by 0xb4lamx** [comment]
this boilerplate follows the [CQRS pattern](https://martinfowler.com/bliki/CQRS.html). therefore commands are not supposed to return DATA. 

use Queries to retrieve data.

**Comment by felixa1996** [comment]
So to save data and get created entity we need to use Command and then using Queries to retrieve data

**Comment by felixa1996** [comment]
But in the controller we dont know when the process is complete
In order to do Query we need to ensure the process is complete

**Comment by 0xb4lamx** [comment]
a 201 HttpStatus is enough to determine whether the request succeeded or not.
